Update README.md (#36)
I changed `const fastify = require('fastify')` in the examples to `const fastify = require('fastify')()` since that seems the (new?) and correct way to work.
If i don't use that i get an error saying `TypeError: fastify.register is not a function`